services:
  - type: web
    name: sathi-mental-health
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 3001
